name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install .NET
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet6

      - name: Install Dafny
        run: |
          wget https://github.com/dafny-lang/dafny/releases/download/v3.10.0/dafny-3.10.0-x64-ubuntu-16.04.zip
          unzip dafny-3.10.0-x64-ubuntu-16.04.zip
          echo $PWD/dafny/ >> $GITHUB_PATH
          PATH=$PATH:$PWD/dafny/ dafny --version

      - name: Check library
        run: ./check.sh
        timeout-minutes: 15
