name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install .NET
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet6

      - name: Install Dafny
        run: |
          wget https://github.com/dafny-lang/dafny/releases/download/v3.9.1/dafny-3.9.1-x64-ubuntu-16.04.zip
          unzip dafny-3.9.1-x64-ubuntu-16.04.zip
          PATH=$PATH:$PWD/dafny/
          echo $PWD
          dafny --version

      - uses: actions/checkout@v3

      - name: Check library
        run: |
          PATH=$PATH:$PWD/dafny/
          cd $GITHUB_WORKSPACE
          ./check.sh
